spring.application.name=food-delivery-mcp-server

server.port=8081

spring.ai.mcp.server.name=food-delivery-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.annotation-scanner.enabled=true
